version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    links:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
      MYSQL_DATABASE: db_kost
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd!
    ports:
      - "3308:3306"
